#根据年月分表demo

spring:
  shardingsphere:
    # 参数配置，显示sql
    props:
      sql:
        show: true
    # 配置数据源
    datasource:
      # 给每个数据源取别名，下面的ds1,ds2,ds3任意取名字
      names: ds0,ds1
      # 给master-ds1每个数据源配置数据库连接信息
      ds0:
        # 配置druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.2.111:3306/ksd-sharding-db?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
        username: root
        password: 123456
        maxPoolSize: 100
        minPoolSize: 5
      # 配置ds2-slave
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.2.112:3306/ksd-sharding-db?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
        username: root
        password: 123456
        maxPoolSize: 100
        minPoolSize: 5
    sharding:
      default-data-source-name: ds0
      tables:
        # ksd_user 逻辑表名
        user_order:
          key-generator:
            # 主键的列明，
            column: orderid
            type: SNOWFLAKE
          # 数据节点：多数据源$->{0..N}.逻辑表名$->{0..N} 相同表
          #          actual-data-nodes: ds$->{0..1}.order$->{2021..2022}${(1..3).collect{t ->t.toString().padLeft(2,'0')} }
          actual-data-nodes: ds0.user_order_$->{2021..2022}${(1..3).collect{t ->t.toString().padLeft(2,'0')} }
            # 拆分库策略，也就是什么样子的数据放入放到哪个数据库中。
            #          database-strategy:
            #            standard:
            #              shardingColumn: yearmonth    # 分片字段（分片键）
          #              preciseAlgorithmClassName: com.example.demo.config.YearMonthShardingAlgorithm # 分片算法表达式
          # 拆分表策略，也就是什么样子的数据放入放到哪个数据表中。
          table-strategy:
            #            inline:
            #              sharding-column: yearmonth    # 分片字段（分片键）
            #              algorithm-expression: user_order_$->{yearmonth} # 分片算法表达式
            standard:
              shardingColumn: yearmonth    # 分片字段（分片键）
              preciseAlgorithmClassName: com.example.demo.config.YearMonthShardingAlgorithm # 分片算法表达式

