# \u670D\u52A1\u7AEF\u53E3
server:
  port: 8082
# \u914D\u7F6Erabbitmq\u670D\u52A1
spring:
  rabbitmq:
    username: admin
    password: admin
    virtual-host: /
    host: 115.29.142.129
    port: 5672